### ISSUE TITLE
Quick option (--quick), when used fails to load key into ssh-agent.

### ISSUE THREAD

**Issue by ffernand** [funtoo/keychain#167]
The quick start command line option, when it fails to detect an ssh-agent, or a key loaded into the ssh-agent, provides a warning that

> * Warning: "Quick start was unsuccessful -- doing a regular start..."

This is fine, except that it fails to load the id_rsa key into the ssh-agent.

A quick example (no pun intended) is found below.

```
user@hostname: ~
$ eval $(keychain --quick --eval id_rsa)

* keychain 2.9.2 ~ http://www.funtoo.org/Funtoo:Keychain
 * Warning: Quick start unsuccessful -- doing regular start...
* Starting ssh-agent...


user@hostname: ~
$ ssh-add -l
The agent has no identities.
```

If I remove the `--quick` option, then it works as intended.

```
user@hostname: ~
$ eval $(keychain --eval id_rsa)

* keychain 2.9.2 ~ http://www.funtoo.org/Funtoo:Keychain
* Starting ssh-agent...
* Adding 1 ssh key(s): /home/user/.ssh/id_rsa
* ssh-add: Identities added: /home/user/.ssh/id_rsa


user@hostname: ~
$ ssh-add -l
256 SHA256:<redacted>
```

Edit: During redacting, did a bad cut-paste job... fixed!

**Comment by danielrobbins** [comment]
Will take a look and see if I can reproduce. Thanks for the bug report!

**Comment by danielrobbins** [comment]
@ffernand can you try reproducing this with the --debug option and see if there's any useful additional output?

**Comment by danielrobbins** [comment]
I haven't reproduced this exact issue yet but I am seeing some issues with --quick. I think there is an error in my quick check subshell logic. Investigating.

**Comment by danielrobbins** [comment]
Please try out keychain from git master and let me know if this resolves the issue. I fixed a bug in the --quick logic.

**Comment by danielrobbins** [comment]
The additional fixes I just committed *should* resolve all outstanding issues with --quick, and also improve informational messages and use of the --debug option with --quick.

**Comment by ffernand** [comment]
Hello @danielrobbins , thanks for looking into this and sorry for the late reply!

The changes found in `master` (`b5eb3a2aa56b17ca7902e8153f9a9daa3ac3a3c6`) is better, but I find that it's still broken.

In one terminal, I'll execute keychain in an agentless environment.

```
user@hostname: ~/src/keychain (master)
$ eval $(./keychain.sh --quick --eval id_rsa)

* keychain ##VERSION## ~ https://www.funtoo.org/Funtoo:Keychain
 * Warning: Quick start unsuccessful -- no agent found...
* Starting ssh-agent...
* Adding 1 ssh key(s): /home/user/.ssh/id_rsa
* ssh-add: Identities added: /home/user/.ssh/id_rsa
```

In another terminal (once the agent exists)... I get the exact same output... it's not detecting the agent.

```
user@hostname: ~/src/keychain (master)
$ eval $(./keychain.sh --quick --eval id_rsa)

* keychain ##VERSION## ~ https://www.funtoo.org/Funtoo:Keychain
 * Warning: Quick start unsuccessful -- no agent found...
* Starting ssh-agent...
* Adding 1 ssh key(s): /home/user/.ssh/id_rsa
* ssh-add: Identities added: /home/user/.ssh/id_rsa
```

So finally, I decide to try using the `--debug` flag to see if I can glean more from debug output, but **it works** (only when using `--debug` though).

```
user@hostname: ~/src/keychain (master)
$ eval $(./keychain.sh --debug --quick --eval id_rsa)

* keychain ##VERSION## ~ https://www.funtoo.org/Funtoo:Keychain
debug> Existing ssh-agent (quick-test1): 810008
* Found existing populated ssh-agent (quick)
```

**Comment by danielrobbins** [comment]
@ffernand first, thanks for testing out the changes.

I would be surprised if --debug affected behavior at all, because all it does is cause extra output to go to stderr. So my initial thoughts on your testing is that --quick is working inconsistently, and you happened to get correct behavior when you attempted it with --debug, but those events aren't correlated. I would assume that, unless you really can never reproduce the problem without --debug.

So, please see if it appears if I am correct, or not. In the mean time, I am going to continue to look at this issue and try to reproduce your issue. When you ran keychain the first time, and it started an ssh-agent, it should have created a pidfile at ~/.keychain/localhost-sh, so you can confirm that. Also do a "ps ax | grep ssh-agent" to see if one is running before running keychain a second time, because it's always possible that when it's saying "no agent found" that the warning is incorrect (this is new code). This will help to troubleshoot what aspect of the logic may be failing for you.

Thanks!

**Comment by ffernand** [comment]
Thanks @danielrobbins.  I can confirm that after repeatedly trying in new terminals, the use of `--debug` seems to _fix_ the issue for me.  This is all using the master branch (b5eb3a2aa56b17ca7902e8153f9a9daa3ac3a3c6).

FYI... system `keychain` was removed and the master version made available to the PATH (hence `./keychain` to `keychain` in these examples).

Below are the following attempts.

## a fresh terminal environment without `ssh-agent` running

```
user@localhost: ~
$ env | grep SSH || echo "no environment"
no environment

user@localhost: ~
$ pkill -f ssh-agent   # killing any running ssh-agent for good measure

user@localhost: ~
$ ps ax | grep '[s]sh-agent' || echo "no agent"
no agent

user@localhost: ~
$ eval $(keychain --quick --eval id_rsa)

* keychain ##VERSION## ~ https://www.funtoo.org/Funtoo:Keychain
 * Warning: Quick start unsuccessful -- no agent found...
* Starting ssh-agent...
* Adding 1 ssh key(s): /home/user/.ssh/id_rsa
Enter passphrase for /home/user/.ssh/id_rsa:
* ssh-add: Identities added: /home/user/.ssh/id_rsa


user@localhost: ~
$ env | grep SSH || echo "no environment"
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXDJnbb5/agent.871874
SSH_AGENT_PID=871875

user@localhost: ~
$ cat ~/.keychain/localhost-sh
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXDJnbb5/agent.871874; export SSH_AUTH_SOCK;
SSH_AGENT_PID=871875; export SSH_AGENT_PID;

user@localhost: ~
$ ps ax | grep '[s]sh-agent' || echo "no agent"
 871875 ?        Ss     0:00 ssh-agent
```

## a new terminal environment with `ssh-agent` running

```
user@localhost: ~
$ env | grep SSH || echo "no environment"
no environment

user@localhost: ~
$ cat ~/.keychain/localhost-sh
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXDJnbb5/agent.871874; export SSH_AUTH_SOCK;
SSH_AGENT_PID=871875; export SSH_AGENT_PID;

user@localhost: ~
$ ps ax | grep '[s]sh-agent' || echo "no agent"
 871875 ?        Ss     0:00 ssh-agent

user@localhost: ~
$ eval $(keychain --quick --eval id_rsa)

* keychain ##VERSION## ~ https://www.funtoo.org/Funtoo:Keychain
 * Warning: Quick start unsuccessful -- no agent found...
* Starting ssh-agent...
* Adding 1 ssh key(s): /home/user/.ssh/id_rsa
Enter passphrase for /home/user/.ssh/id_rsa:
* ssh-add: Identities added: /home/user/.ssh/id_rsa


user@localhost: ~
$ env | grep SSH || echo "no environment"
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXu1QRpD/agent.872865
SSH_AGENT_PID=872866

user@localhost: ~
$ cat ~/.keychain/localhost-sh
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXu1QRpD/agent.872865; export SSH_AUTH_SOCK;
SSH_AGENT_PID=872866; export SSH_AGENT_PID;

user@localhost: ~
$ ps ax | grep '[s]sh-agent' || echo "no agent"
 871875 ?        Ss     0:00 ssh-agent
 872866 ?        Ss     0:00 ssh-agent
```

## a third attempt with `ssh-agent` running and the use of the `--debug` flag.
```
user@localhost: ~
$ env | grep SSH || echo "no environment"
no environment

user@localhost: ~
$ cat ~/.keychain/localhost-sh
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXu1QRpD/agent.872865; export SSH_AUTH_SOCK;
SSH_AGENT_PID=872866; export SSH_AGENT_PID;

user@localhost: ~
$ ps ax | grep '[s]sh-agent' || echo "no agent"
 871875 ?        Ss     0:00 ssh-agent
 872866 ?        Ss     0:00 ssh-agent

user@localhost: ~
$ eval $(keychain --debug --quick --eval id_rsa)

* keychain ##VERSION## ~ https://www.funtoo.org/Funtoo:Keychain
debug> Existing ssh-agent (quick-test1): 872866
* Found existing populated ssh-agent (quick)


user@localhost: ~
$ env | grep SSH || echo "no environment"
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXu1QRpD/agent.872865
SSH_AGENT_PID=872866

user@localhost: ~
$ cat ~/.keychain/localhost-sh
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXu1QRpD/agent.872865; export SSH_AUTH_SOCK;
SSH_AGENT_PID=872866; export SSH_AGENT_PID;

user@localhost: ~
$ ps ax | grep '[s]sh-agent' || echo "no agent"
 871875 ?        Ss     0:00 ssh-agent
 872866 ?        Ss     0:00 ssh-agent
```

Since then, I've tried a number of attempts and it _seems_ to work with `--debug` turned on.  I'm happy to try anything else you'd like to see.

**Comment by danielrobbins** [comment]
OK -- I'll try to track down why this is. Thanks for testing.

**Comment by danielrobbins** [comment]
OK, I can reproduce this...

**Comment by danielrobbins** [comment]
OK, the problem was in my new code added to ssh_envcheck -- the new method I am using for setting quiet/debug mode doesn't work. I know how to fix it.

**Comment by danielrobbins** [comment]
OK, new fixes incoming. This should resolve it and is working over here.

**Comment by ffernand** [comment]
Thank you @danielrobbins , IT WORKS!

I tried out commit 5efdda1c93433cec745bc188b3566ebb63af0380 (which I believe is a few commits ahead of your fix for this ticket) and it works great!

Thank you very much!

**Comment by danielrobbins** [comment]
@ffernand Thanks for testing out the fixes. I will get this out in a new release sometime today.
